Repository Pive-Guyz/ondam-backend, pull requests merged in 2025-04, with the labels that each got.

#6 [feat] ChatGPT API 연동 및 응답 생성
  .gitignore
  ondam-backend/build.gradle
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/controller/AnalysisController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/dto/ChatCompletionDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/dto/ChatRequestMsgDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/AnalysisService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/AnalysisServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/config/ChatGPTConfig.java
Labels: :sparkles: enhancement, :test_tube: test

#9 [feat] counselee api
  .gitignore
  ondam-backend/build.gradle
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/config/WebConfig.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/response/ErrorResponse.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/application/controller/CounseleeCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/application/dto/CounseleeCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/application/service/CounseleeCommandService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/application/service/CounseleeCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/domain/aggregate/entity/CounseleeEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/domain/aggregate/vo/Birthday.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/domain/aggregate/vo/Gender.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/domain/aggregate/vo/PhoneNumber.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/command/domain/repository/CounseleeRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/query/controller/CounseleeQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/query/dto/CounseleeQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/query/mapper/CounseleeMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/query/service/CounseleeQueryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counselee/query/service/CounseleeQueryServiceImpl.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/counselee/query/mapper/CounseleeMapper.xml
Labels: :sparkles: enhancement

#25 [feat] 신고 도메인 커맨드 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/controller/ReportCategoryCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/controller/ReportCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/controller/ReportController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/dto/ReportCategoryCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/dto/ReportDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/dto/ReportDiaryCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/dto/ReportReplyCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/dto/ReportStatusUpdateCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/service/ReportCategoryCommandService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/service/ReportCategoryCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/service/ReportCommandService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/service/ReportCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/application/service/ReportService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/aggregate/Report.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/aggregate/ReportCategory.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/aggregate/ReportStatus.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/aggregate/ReportStatusConverter.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/repository/ReportCategoryRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/repository/ReportRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/service/ReportDomainService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/aggregate/Diary.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/aggregate/Reply.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/repository/DiaryRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/repository/ReplyRepository.java
Labels: :sparkles: enhancement

#18 [feat] 신고 도메인 조회 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/controller/ReportController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/ReportCategoryQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/ReportContentQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/ReportDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/ReportDetailQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/ReportListQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/enums/InitFile
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/dto/enums/ReportStatus.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/mapper/ReportMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/mapper/ReportQueryMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/service/ReportQueryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/service/ReportQueryServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/service/ReportService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/service/ReportServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/query/typehandler/ReportStatusTypeHandler.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/report/query/mapper/ReportQueryMapper.xml
  ondam-backend/src/test/java/com/piveguyz/ondambackend/report/ReportQueryTest.java
Labels: :sparkles: enhancement

#29 [feat] 일기 발송 기록 id 타입 변경
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diary/query/mapper/DiaryDAO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/command/application/controller/DiaryRecordController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/command/application/dto/DiaryRecordDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/query/dto/DiaryRecordQueryDTO.java
Labels: 🔧 refactoring

#33 [refactor] 신고 승인 컨텐츠 블라인드 처리 기능 수정
  ondam-backend/src/main/java/com/piveguyz/ondambackend/OndamBackendApplication.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/command/domain/service/ReportDomainService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/aggregate/Diary.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/aggregate/Reply.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/repository/DiaryRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/report/temp/repository/ReplyRepository.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/counselee/query/mapper/CounseleeMapper.xml
  ondam-backend/src/test/java/com/piveguyz/ondambackend/report/ReportCommandTest.java
Labels: 🔧 refactoring

#35 [feat] 회원가입 기능 구현
  ondam-backend/build.gradle
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/controller/MemberCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/controller/MemberController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/dto/MemberDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberServiceImp.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/config/AppConfig.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/aggregate/Member.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/aggregate/MemberEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/repository/MemberRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/vo/RequestRegistMembersVO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/controller/MemberQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/dto/MemberDTO.java
Labels: :sparkles: enhancement

#37 feat : 상담 API
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/exceptions/CounselNotFoundException.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/exceptions/CounseleeNotFoundException.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/exceptions/MemberNotFoundException.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/controller/CounselCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/controller/CounselController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/dto/CounselCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/dto/CounselDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/service/CounselCommandService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/service/CounselCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/service/CounselService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/Counsel.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/VO/CounselContent.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/VO/CounselOpinion.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/VO/CounselTime.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/VO/Weather.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/entity/CounselEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/repository/CounselRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/controller/CounselController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/controller/CounselQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/dto/CounselDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/dto/CounselQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/dto/enums/InitFile
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/mapper/CounselMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/service/CounselQueryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/service/CounselQueryServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/service/CounselService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/service/CounselServiceImpl.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/counsel/query/mapper/CounselMapper.xml
Labels: :sparkles: enhancement

#44 [refactor] analysis 도메인 커스텀 exception 사용하도록 수정
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/controller/AnalysisCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/AnalysisService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/AnalysisServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/exceptions/AnalysisExceptionHandler.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/exceptions/InvalidCounselContentException.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/config/exceptionhandler/GlobalExceptionHandler.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/common/response/GlobalErrorResponse.java
Labels: 🔧 refactoring

#47 [feat] 회원 로그인 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/aggregate/MemberQueryEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/controller/MemberQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/vo/RequestLoginVO.java
Labels: :sparkles: enhancement

#48 [feat] 분석 도메인의 감정 카테고리, 감정 cud 기능 구현
  db/createTable.sql
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/controller/AnalysisCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/controller/EmotionCategoryCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/controller/EmotionCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/dto/EmotionCategoryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/dto/EmotionDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/EmotionCategoryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/EmotionCategoryServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/EmotionService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/EmotionServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/aggregate/Emotion.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/aggregate/EmotionCategory.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/repository/EmotionAnalysisRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/repository/EmotionCategoryRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/repository/EmotionRepository.java
Labels: :sparkles: enhancement

#56 [feat] 회원 탈퇴 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/controller/MemberCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/dto/ChangePasswordDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/aggregate/MemberEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/repository/MemberRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/aggregate/MemberQueryEntity.java
Labels: :sparkles: enhancement

#59 [feat] 회원 비밀번호 수정 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/controller/MemberCommandController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/dto/ChangePasswordDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberService.java
Labels: :sparkles: enhancement

#57 [refactor] counsel에 누락된 counselType 속성 추가
  db/createTable.sql
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/dto/CounselCommandDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/application/service/CounselCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/command/domain/aggregate/entity/CounselEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/counsel/query/dto/CounselQueryDTO.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/counsel/query/mapper/CounselMapper.xml
Labels: 🔧 refactoring

#61 [refactor] 감정 분석 결과 데이터 수정
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/AnalysisServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/query/dto/EmotionAnalysisDTO.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/analysis/query/mapper/AnalysisResultMapper.xml
Labels: 🔧 refactoring

#63 feat: 선택한 회원 조회 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/controller/MemberQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberServiceImpl.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.xml
Labels: :sparkles: enhancement

#60 [feat] 일기 발송 기록 만료 기능 구현 / [refactor] Mapper 수정
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/command/application/service/DiaryRecordService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/command/domain/repository/DiaryRecordRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/scheduler/DiaryScheduler.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/diary/query/mapper/DiaryMapper.xml
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/diaryRecord/query/mapper/DiaryRecordMapper.xml
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/reply/query/mapper/ReplyMapper.xml
Labels: :sparkles: enhancement, 🔧 refactoring

#65 [feat] point 변동 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/command/application/service/DiaryRecordService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/controller/MemberQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/dto/MemberQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberQueryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberServiceImpl.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.xml
Labels: :sparkles: enhancement

#67 [feat] 포인트 변동 기능 구현 / [refactor] MemberMapper.xml 데이터 형태 변경
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diary/command/application/service/DiaryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberCommandServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/application/service/MemberService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/command/domain/aggregate/MemberEntity.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/dto/MemberQueryDTO.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/reply/command/application/service/ReplyService.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.xml
Labels: :sparkles: enhancement, 🔧 refactoring

#68 [test] 분석 도메인 테스트 코드 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/repository/EmotionAnalysisRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/domain/repository/EmotionCategoryRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/query/controller/AnalysisQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/query/service/AnalysisQueryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/query/service/AnalysisQueryServiceImpl.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/analysis/AnalysisCommandTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/analysis/AnalysisQueryTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/analysis/EmotionCategoryCommandTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/analysis/EmotionCommandTest.java
Labels: :test_tube: test

#72 [chore] gpt 에러 메세지, 프롬프트 수정
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/command/application/service/AnalysisServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/analysis/exceptions/InvalidCounselContentException.java
Labels: :zap: Update

#71 [test] command test 구현
  ondam-backend/src/test/java/com/piveguyz/ondambackend/member/MemberCommandTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/member/MemberQueryTest.java
Labels: :test_tube: test

#74 [test] 일기 도메인 테스트 케이스 생성
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diary/command/domain/repository/DiaryRepository.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/diaryRecord/command/application/service/DiaryRecordService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/reply/command/domain/repository/ReplyRepository.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/diary/DiaryCommandTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/diary/DiaryQueryTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/diaryRecord/DiaryRecordCommandTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/diaryRecord/DiaryRecordQueryTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/reply/ReplyCommandTest.java
  ondam-backend/src/test/java/com/piveguyz/ondambackend/reply/ReplyQueryTest.java
Labels: :test_tube: test

#76 feat: 회원 아이디,비밀번호 찾기 기능 구현
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/controller/MemberQueryController.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberQueryService.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/service/MemberServiceImpl.java
  ondam-backend/src/main/java/com/piveguyz/ondambackend/member/query/vo/RequestFindIdVO.java
  ondam-backend/src/main/resources/com/piveguyz/ondambackend/member/query/mapper/MemberMapper.xml
Labels: :sparkles: enhancement
